require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/SymbolArray:
  Exclude:
    - Rakefile
